version: "3.3"

services:
  bot:
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    restart: unless-stopped
    command: bash -c "python main.py"
    env_file:
      - docker/.dockerenv

  mongo:
      image: mongo
      restart: always
      env_file:
        - docker/.dockerenv

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - docker/.dockerenv
