version: "3.3"

services:
  bot:
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    restart: unless-stopped
    command: bash -c "python main.py"
    env_file:
      - docker/.dockerenv
