name: Validate code and deploy

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1

      - name: install dependencies
        run: |
          cd ./src
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --deploy --system --ignore-pipfile

      - name: run pytest
        run: |
          cd ./src
          pytest tests/

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1

      - name: install dependencies
        run: |
          cd ./src
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --deploy --system --ignore-pipfile

      - name: run ruff
        run: ruff ./src

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1

      - name: install dependencies
        run: |
          cd ./src
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --deploy --system --ignore-pipfile

      - name: run mypy
        run: |
          cd ./src
          mypy .

  deploy:
    needs: [tests, linter, typing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          directory: ./docker
          file_name: .dockerenv
          fail_on_empty: true

      - name: login in server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./"
          target: "~/where-is-my-card"

      - name: launch bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd where-is-my-card
            make reload