name: Deploy

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Code validation"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: generate envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          directory: ./docker
          file_name: .dockerenv
          fail_on_empty: true

      - name: login in server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./"
          target: "~/where-is-my-card"

      - name: launch bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd where-is-my-card
            make reload